### ISSUE TITLE
Deactivation of Duress if you click on the wipe tab

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Duress#7] opened 2022-06-27 23:45 UTC
When changing tabs, it descends duress. There is no need to touch to deactivate just view the wiper tab.

![1](https://user-images.githubusercontent.com/6586244/176055939-565a4e6d-e527-4d74-9aed-bdc965a99780.jpeg)
![2](https://user-images.githubusercontent.com/6586244/176055960-9a8c15d9-901a-4dd1-ae59-8d19931f822a.jpeg)
![3](https://user-images.githubusercontent.com/6586244/176055972-2e12703c-c7a2-4c06-bc6f-ebc965a23801.jpeg)

**Comment by x13a** [comment] 2022-06-28 00:07
Yes, it is by design. When switching tab (Broadcast/Wipe), the app mode
changes, I programmatically disable the app to prevent wipe for people who
are wanting to send a broadcast.

**Comment by x13a** [comment] 2022-06-28 00:29
If you need to wipe an Embedded SIM's too then you have to use Wasted.
I have not added it. Duress only wipes data. It is a common case for
most.

**Comment by xyz-nobody** [comment] 2022-06-28 00:30
ok sorry I didn't understand.
It's great how it works. Duress can work in standalone without Wasted.

Maybe you should write a little sentence in the tab to make it clearer. Like: Standalone Mode

Thk for this fucking good app

**Comment by xyz-nobody** [comment] 2022-06-28 01:12
it's true that internet can be lost for many different reasons, but it's a real inactivity :)

If I travel I know I have to increase the time.
Otherwise if I don't have internet for X hours or Days I know there is a problem.

My phone has been stolen, an attacker has my phone.

**Comment by x13a** [comment] 2022-07-02 08:31
Resolved, closing

**Closed by x13a** 2022-07-02 08:31 UTC
